FROM quay.io/fedora-ostree-desktops/kinoite:43 as rootfs

LABEL org.opencontainers.image.title="Fedora Kinoite UKI"
LABEL org.opencontainers.image.source="https://github.com/travier/fedora-kinoite"
LABEL org.opencontainers.image.licenses="MIT"
LABEL quay.expires-after=""

RUN --mount=type=tmpfs,target=/run \
    --mount=type=tmpfs,target=/tmp \
    --mount=type=tmpfs,target=/var \
    <<EORUN
set -euo pipefail
set -x

# We don't want openh264
rm -f "/etc/yum.repos.d/fedora-cisco-openh264.repo"

# Install fsverity utils to make it easier to check things
# Install systemd-boot (will be replaced by the signed version later)
dnf install -y fsverity-utils systemd-boot-unsigned

# Uninstall bootupd (no support for systemd-boot yet)
rpm -e bootupd
rm -vrf "/usr/lib/bootupd/updates"

# mkdir -p "/usr/lib/bootc/kargs.d"
cat > "/usr/lib/bootc/kargs.d/10-rootfs-rw.toml" << 'EOF'
# Mount the root filesystem read-write
kargs = ["rw"]
EOF

# Default to btrfs
# mkdir -p "/usr/lib/bootc/install"
cat > "/usr/lib/bootc/install/80-rootfs.toml" << 'EOF'
[install.filesystem.root]
type = "btrfs"
EOF

# Dracut will always fail to set security.selinux xattrs at build time
# https://github.com/dracut-ng/dracut-ng/issues/1561
cat > "/usr/lib/dracut/dracut.conf.d/20-bootc-base.conf" << 'EOF'
export DRACUT_NO_XATTR=1
EOF

# Enable composefs backend in dracut
cat > "/usr/lib/dracut/dracut.conf.d/20-bootc-composefs.conf" << 'EOF'
add_dracutmodules+=" bootc "
EOF

# Rebuild the initramfs to get bootc-initramfs-setup
kver=$(cd "/usr/lib/modules" && echo *)
dracut -vf --install "/etc/passwd /etc/group" "/usr/lib/modules/$kver/initramfs.img" "$kver"

# Prepare folders in /boot
mkdir -p /boot/EFI/Linux
EORUN

COPY /systemd-bootx64.efi /usr/lib/systemd/boot/efi/systemd-bootx64.efi

FROM rootfs as lint
RUN bootc container lint

FROM scratch as rootfs-clean
COPY --from=rootfs / /
LABEL containers.bootc 1
LABEL ostree.bootable 1
ENV container=oci
STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]

FROM quay.io/fedora-ostree-desktops/base-atomic:43 as sealed-uki
RUN --mount=type=tmpfs,target=/run \
    --mount=type=bind,from=rootfs-clean,src=/,target=/run/target \
    --mount=type=secret,id=secureboot_key \
    --mount=type=secret,id=secureboot_cert <<EORUN
set -euo pipefail
set -x

# We don't want openh264
rm -f "/etc/yum.repos.d/fedora-cisco-openh264.repo"

# Install ukify & signing tools
dnf install -y systemd-ukify sbsigntools
dnf clean all

target="/run/target"
output="/boot/EFI/Linux"
secrets="/run/secrets"

mkdir -p /boot/EFI/Linux

# Find the kernel version (needed for output filename)
kver=$(bootc container inspect --rootfs "${target}" --json | jq -r '.kernel.version')
if [ -z "$kver" ] || [ "$kver" = "null" ]; then
  echo "Error: No kernel found" >&2
  exit 1
fi

# Baseline ukify options
ukifyargs=(--measure
           --json pretty
           --output "${output}/${kver}.efi")

# Signing options, we use sbsign by default
ukifyargs+=(--signtool sbsign
            --secureboot-private-key "${secrets}/secureboot_key"
            --secureboot-certificate "${secrets}/secureboot_cert")

# Baseline container ukify options
containerukifyargs=(--rootfs "${target}")

# Build the UKI using bootc container ukify
# This computes the composefs digest, reads kargs from kargs.d, and invokes ukify
bootc container ukify "${containerukifyargs[@]}" "${missing_verity[@]}" -- "${ukifyargs[@]}"
EORUN

FROM rootfs-clean as pre-final
RUN --mount=type=bind,from=sealed-uki,target=/_mount <<EORUN
cp -r /_mount/boot/* /boot/
EORUN

FROM rootfs-clean as final
COPY --from=pre-final /boot/EFI/Linux /boot/EFI/Linux
