FROM registry.fedoraproject.org/fedora:40 AS builder

RUN dnf update -y && \
    dnf install -y rust cargo && \
    cargo install bandwhich
RUN mv /root/.cargo/bin/bandwhich /

# Location not final and subject to change!
FROM quay.io/fedora-ostree-desktops/kinoite:40

LABEL org.opencontainers.image.title="Fedora Kinoite"
LABEL org.opencontainers.image.description="Customized image of Fedora Kinoite"
LABEL org.opencontainers.image.source="https://github.com/travier/fedora-kinoite"
LABEL org.opencontainers.image.licenses="MIT"

# Copy bandwhich from builder container
COPY --from=builder /bandwhich /usr/bin/bandwhich

RUN rpm-ostree install \
        bwm-ng \
        distrobox \
        htop \
        igt-gpu-tools \
        iotop \
        iwd \
        krb5-workstation \
        libvirt-daemon \
        libvirt-daemon-config-network \
        libvirt-daemon-driver-interface \
        libvirt-daemon-driver-network \
        libvirt-daemon-driver-nodedev \
        libvirt-daemon-driver-nwfilter \
        libvirt-daemon-driver-qemu \
        libvirt-daemon-driver-secret \
        libvirt-daemon-driver-storage-core \
        libvirt-dbus \
        netcat \
        qemu-kvm \
        sysprof \
        vim \
        wireguard-tools \
        zsh \
    && \
    wget \
        "https://kojipkgs.fedoraproject.org//work/tasks/9015/115339015/plasma-discover-6.0.2-2.fc40.x86_64.rpm" \
        "https://kojipkgs.fedoraproject.org//work/tasks/9015/115339015/plasma-discover-flatpak-6.0.2-2.fc40.x86_64.rpm" \
        "https://kojipkgs.fedoraproject.org//work/tasks/9015/115339015/plasma-discover-libs-6.0.2-2.fc40.x86_64.rpm" \
        "https://kojipkgs.fedoraproject.org//work/tasks/9015/115339015/plasma-discover-notifier-6.0.2-2.fc40.x86_64.rpm" \
        "https://kojipkgs.fedoraproject.org//work/tasks/9015/115339015/plasma-discover-rpm-ostree-6.0.2-2.fc40.x86_64.rpm" \
    && \
    rpm-ostree override replace ./plasma-discover-*.rpm \
    && \
    rm -v plasma-discover-*.rpm \
    && \
    systemctl enable libvirtd.socket \
    && \
    rm -rf /var/lib/unbound/root.key

# Copy custom config to /usr & /etc
COPY usr usr
COPY etc etc

RUN ostree container commit
