FROM localhost/fedora-kinoite:latest

# - Remove ostree-grub2, setup composefs, rebuild initramfs
# - Install bootupd and generate metadata
RUN rpm-ostree override remove ostree-grub2 && \
    echo -e "[composefs]\nenabled=yes" >> /usr/lib/ostree/prepare-root.conf && \
    export KERNEL_VERSION="$(rpm -qa kernel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}')" && \
    stock_arguments=$(lsinitrd "/lib/modules/${KERNEL_VERSION}/initramfs.img"  | grep '^Arguments: ' | sed 's/^Arguments: //') && \
    mkdir -p /tmp/dracut /var/roothome && \
    bash <(/usr/bin/echo "dracut $stock_arguments") && \
    rm -rf /var/* /tmp/*  && \
    mv -v /boot/initramfs*.img "/lib/modules/${KERNEL_VERSION}/initramfs.img" \
    && \
    rpm-ostree install bootupd && \
    /usr/bin/bootupctl backend generate-update-metadata \
    && \
    rpm-ostree cleanup --repomd \
    && \
    ostree container commit
