# Location not final and subject to change!
FROM quay.io/fedora-ostree-desktops/kinoite:43

LABEL org.opencontainers.image.title="Fedora Kinoite"
LABEL org.opencontainers.image.description="Customized image of Fedora Kinoite"
LABEL org.opencontainers.image.source="https://github.com/travier/fedora-kinoite"
LABEL org.opencontainers.image.licenses="MIT"
LABEL quay.expires-after=""

# Copy custom config to /etc
COPY etc etc

# - Remove SetUID/SetGID bits
RUN --mount=type=secret,id=cert \
    <<EORUN
set -xeuo pipefail
chmod ug-s \
    /usr/bin/chage \
    /usr/bin/chfn \
    /usr/bin/chsh \
    /usr/bin/gpasswd \
    /usr/bin/newgrp \
    /usr/bin/passwd \
    /usr/bin/vmware-user-suid-wrapper
bootc container lint
EORUN
