#!/bin/sh
# SPDX-FileCopyrightText: 2019 Aleix Pol Gonzalez <aleixpol@kde.org>
# SPDX-FileCopyrightText: 2021 Nate Graham <nate@kde.org>
#
# SPDX-License-Identifier: GPL-2.0-or-later

set -e

# Make built-from-source sessions appear in login screen
sudo install --mode=644 -D kde/build/plasma-workspace/login-sessions/plasmax11-dev6.desktop --target-directory=/usr/local/share/xsessions
sudo install --mode=644 -D kde/build/plasma-workspace/login-sessions/plasmawayland-dev6.desktop --target-directory=/usr/local/share/wayland-sessions
install kde/build/plasma-workspace/prefix.sh /usr/src/kde/usr/lib64/libexec/plasma-dev-prefix.sh
install kde/build/plasma-workspace/login-sessions/startplasma-dev.sh /usr/src/kde/usr/lib64/libexec

# Make the system DBus able to see any new DBus files that have been added to
# the built-from-source plasma session which are not yet present in the system
# DBus locations. Because some distros have security policies which prevent the
# use of DBus files in a user's homedir, and even symlinks outside,
# we have to copy the files into a system-owned location.
sudo mkdir -p /opt/kde-dbus-scripts/
sudo cp -r /usr/src/kde/usr/share/dbus-1/* /opt/kde-dbus-scripts/

old_file='/etc/dbus-1/session-local.conf'
[ -e $old_file ] && grep --quiet '/opt/kde-dbus-scripts' $old_file && sudo rm -v $old_file

cat > /tmp/00-plasma.conf << EOF
<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-Bus Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<!-- This file is autogenerated by Plasma's install-sessions.sh; Changes may get overwritten! -->
<busconfig>
    <servicedir>/opt/kde-dbus-scripts/services</servicedir>
    <includedir>/opt/kde-dbus-scripts/session.d/</includedir>
    <standard_session_servicedirs/>
</busconfig>
EOF
sudo mkdir -p /etc/dbus-1/session.d/
sudo mv /tmp/00-plasma.conf /etc/dbus-1/session.d/
