# Location not final and subject to change!
FROM quay.io/fedora-ostree-desktops/kinoite:rawhide

LABEL org.opencontainers.image.title="Fedora Kinoite"
LABEL org.opencontainers.image.description="Fedora Kinoite Live ISO"
LABEL org.opencontainers.image.source="https://github.com/travier/fedora-kinoite"
LABEL org.opencontainers.image.licenses="MIT"
LABEL quay.expires-after=""

# Missing anaconda-tools
RUN rpm-ostree install \
        anaconda \
        anaconda-install-env-deps \
        anaconda-live \
        grub2-efi-x64-cdboot \
        livesys-scripts \
    && \
    systemctl enable livesys.service livesys-late.service \
    && \
    sed -i 's/^livesys_session=.*/livesys_session="kde"/' /etc/sysconfig/livesys \
    && \
    ostree container commit
