FROM registry.fedoraproject.org/fedora:40 AS builder

RUN dnf update -y && \
    dnf install -y rust cargo && \
    cargo install bandwhich
RUN mv /root/.cargo/bin/bandwhich /

FROM registry.fedoraproject.org/fedora:40

COPY --from=builder /bandwhich /usr/bin/bandwhich
